### ISSUE TITLE
Suggestion: Use submodules to link git repos instead of copying, the repos could get updated

### ISSUE THREAD

**Issue by firefish111** [Repl-it-Coders/projects#3]
read the title

**Comment by firefish111** [comment]
@whippingdot @HoangTuan110

**Comment by whippingdot** [comment]
@firefish111 I don't understand, what do you mean by link using submodules.

**Comment by firefish111** [comment]
Git has this feature where you can add sirectories that contain the entire contents of another repo, although the directories don't actually exist.
Example:
![image](https://user-images.githubusercontent.com/33234914/103458690-726dbd80-4d02-11eb-8084-3676b7986af7.png)
That directory `dusk` is effectively a symlink to the repo firefish111/dusk, and when you clone the repo, the act of cloning clones BOTH of the repos into their respective directories.

**Comment by whippingdot** [comment]
Ok, can you edit and make the subdirectories work(if you haven't already). i don't know how to.

**Comment by firefish111** [comment]
ok I'm-a open a pr

**Comment by whippingdot** [comment]
Wait why, can't you just edit directly. Why do you need a pr

**Comment by firefish111** [comment]
# REEEE I CAN'T BECAUSE I CAN'T FIND A REPO WITH THE CALCULATOR ON
@HoangTuan110 Can you move it to a repo on your own account please?

**Comment by whippingdot** [comment]
I know I saw your post on Node.js. You should delete that btw. It is better if you only mention him/her here instead of there

**Comment by whippingdot** [comment]
Also @firefish111 next time put suggestions in the discussions. You can even @ mention me if you want. We can then convert the discussion into an issue if we want to implement the suggestion.

**Comment by firefish111** [comment]
@whippingdot Which disussions tab?

**Comment by whippingdot** [comment]
![image](https://user-images.githubusercontent.com/64354499/103479003-65c79300-4df0-11eb-8dd7-bae884c0078e.png)

**Comment by firefish111** [comment]
Ah ok

**Comment by whippingdot** [comment]
@HoangTuan110 are you there????

**Comment by firefish111** [comment]
Let's ping him on replit

**Comment by whippingdot** [comment]
He left the whole org bro...Me sad....

**Comment by programmeruser2** [comment]
I have a project I would like to add, you could try it on that. https://github.com/programmeruser2/os 
@firefish111  @whippingdot

**Comment by whippingdot** [comment]
Ok, wait, lemme search online how to do this. Even I have a project I wanna put.
